name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref
        run: echo ${{ github.ref }}

      - name: Print github
        run: echo ${{ github }}

      - name: Print node version
        run: node -v
