name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref
        # format: refs/heads/<branch_name>
        # Condition to run only on develop branch -> if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo ${{ github.ref }}
        
      - name: Install yarn
        run: npm install --global yarn

      - name: Print yarn version
        run: yarn -v
